# Generated by Django 6.0.3 on 2026-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_make_model', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service', models.CharField(choices=[('essential_detail', 'Essential Detail'), ('premium_detail', 'Premium Detail'), ('showroom_detail', 'Showroom Detail'), ('maintenance_wash', 'Maintenance Wash'), ('exterior_detail', 'Exterior Detail'), ('paint_refresh', 'Paint Refresh'), ('interior_refresh', 'Interior Refresh'), ('deep_interior', 'Deep Interior'), ('seat_carpet_reset', 'Seat & Carpet Reset')], max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00-11:00', '9:00 AM - 11:00 AM'), ('12:00-02:00', '12:00 PM - 2:00 PM'), ('03:00-05:00', '3:00 PM - 5:00 PM')], max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['booking_date', 'time_slot'],
                'unique_together': {('booking_date', 'time_slot')},
            },
        ),
    ]
