# Generated by Django 6.0.3 on 2026-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_closeddate_weeklyavailability_blockedtimeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='detail_location',
            field=models.CharField(default='Location not provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('09:00-11:00', '9:00 AM - 11:00 AM'), ('11:30-01:30', '11:30 AM - 1:30 PM'), ('02:00-04:00', '2:00 PM - 4:00 PM')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('booking_date', 'time_slot'), name='unique_booking_slot'),
        ),
    ]
