# Generated by Django 6.0.3 on 2026-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='missingemail@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
